In [15]:
import numpy as np

# Create a 3D array of shape (2, 3, 4) filled with zeros
arr = np.zeros((2, 3, 4))

# Set some elements to 1
arr[0, 1, 2] = 1
arr[1, 2, 3] = 1

# Print the array
print(arr)


[[[0. 0. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 1.]]]


In [16]:
voxel_size = 1.5  # in mm
brain_vol = np.count_nonzero(arr) * (voxel_size ** 3)

In [17]:
vector = arr.ravel()
imgs = []

In [30]:
# turn to matrix, then to 1D array
img_vec = np.append(vector, brain_vol)
img_vec = np.append(121323123, img_vec)
imgs.append(img_vec)

# stack the vectors into a 2D array
X = np.vstack(imgs)


In [31]:
img_vec

array([1.21323123e+08, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.00000000e+00, 6.75000000e+00])

In [25]:
len(vector)

24

In [26]:
len(img_vec)

26

In [27]:
X

array([[1.21323123e+08, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 6.75000000e+00]])

In [ ]:
x